[package]
name = "rs-csv2seeds2cbors"
version = "0.1.0"
edition = "2024"

exclude = [
]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
unwrap_used = "forbid"
expect_used = "forbid"
panic = "forbid"

[[bin]]
name = "csv2seeds2cbors"

[dependencies.csv]
version = "1.4.0"
default-features = false
features = [
]

[dependencies.wasmtime]
version = "46"
default-features = false
features = [
  "wat",
  "runtime",
  "cranelift",
]
